# Generated by Django 3.2.1 on 2021-06-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linked_in',
            field=models.URLField(null=True),
        ),
    ]
