# Generated by Django 3.2.1 on 2021-06-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
