# Generated by Django 3.2.1 on 2021-06-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_postgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
