# Generated by Django 3.2.1 on 2021-06-22 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0011_post_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgroup',
            name='admin',
        ),
        migrations.AddField(
            model_name='postgroup',
            name='admin',
            field=models.ManyToManyField(related_name='group', to=settings.AUTH_USER_MODEL),
        ),
    ]
