# Generated by Django 3.2.1 on 2021-06-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20210622_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postgroup',
            old_name='admin',
            new_name='admin_users',
        ),
    ]
