# Generated by Django 3.2.1 on 2021-06-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_rename_admin_postgroup_admin_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgroup',
            name='admin_users',
        ),
    ]
