# Generated by Django 3.2.1 on 2021-06-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_remove_postgroup_admin_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
        migrations.DeleteModel(
            name='PostGroup',
        ),
    ]
