# Generated by Django 3.2.1 on 2021-07-12 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_alter_clubpost_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='grp_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_posts', to='post.clubpost'),
        ),
    ]
